from typing import List, Optional

from pydantic import BaseModel, Field


class RecommendationResult(BaseModel):
    """
    Final recommendation generated by the Recommendation Agent.
    This is the output presented to the Security Analyst.
    """

    recommended_action: Optional[str] = Field(
        default=None,
        description="Primary action recommended by the AI"
    )

    action_priority: Optional[str] = Field(
        default=None,
        description="Critical, High, Medium or Low"
    )

    business_impact: Optional[str] = Field(
        default=None,
        description="Expected business impact if recommendation is not followed"
    )

    reasoning: List[str] = Field(
        default_factory=list,
        description="Reasons supporting the recommendation"
    )

    supporting_evidence: List[str] = Field(
        default_factory=list,
        description="Evidence collected during analysis"
    )

    confidence: Optional[float] = Field(
        default=None,
        ge=0,
        le=100,
        description="Confidence score"
    )

    alternative_actions: List[str] = Field(
        default_factory=list,
        description="Other possible actions"
    )

    follow_up_actions: List[str] = Field(
        default_factory=list,
        description="Recommended next investigation steps"
    )