import { useEffect, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { analyzeIncident } from '../services/incidentService';
import Card from '../components/common/Card';
import Loader from '../components/common/Loader';
import EmptyState from '../components/common/EmptyState';

const renderSection = (title: string, data: Record<string, unknown>) => (
  <Card title={title}>
    <div className="space-y-3">
      {Object.entries(data).map(([key, value]) => (
        <div key={key} className="grid gap-2 sm:grid-cols-[180px_1fr]">
          <p className="text-sm font-semibold text-text">{key}</p>
          <p className="text-sm text-muted">{JSON.stringify(value, null, 2)}</p>
        </div>
      ))}
    </div>
  </Card>
);

const AnalysisPage = () => {
  const [searchParams] = useSearchParams();
  const incidentId = searchParams.get('id');
  const [analysis, setAnalysis] = useState<Record<string, Record<string, unknown>> | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!incidentId) return;
    const fetchAnalysis = async () => {
      setIsLoading(true);
      try {
        const data = await analyzeIncident(incidentId);
        setAnalysis({
          incidentSummary: data.incidentSummary,
          context: data.context,
          riskAnalysis: data.riskAnalysis,
          recommendations: data.recommendations,
          approval: data.approval,
        });
      } catch (_err) {
        setError('Unable to load analysis.');
      } finally {
        setIsLoading(false);
      }
    };
    fetchAnalysis();
  }, [incidentId]);

  if (!incidentId) {
    return <EmptyState title="No incident selected" description="Select an incident from the list to run analysis." />;
  }

  if (isLoading) {
    return <Loader />;
  }

  if (error || !analysis) {
    return <div className="rounded-3xl border border-white/10 bg-card p-8 text-center text-muted">{error || 'No analysis available.'}</div>;
  }

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-semibold text-text">AI Analysis</h1>
        <p className="text-sm text-muted">Review the incident analysis generated by the backend.</p>
      </div>
      {Object.entries(analysis).map(([section, data]) => renderSection(section, data))}
    </div>
  );
};

export default AnalysisPage;
