import { useEffect, useState } from 'react';
import { motion } from 'framer-motion';
import { useSearchParams } from 'react-router-dom';
import { analyzeIncident } from '../services/incidentService';
import Card from '../components/common/Card';
import Loader from '../components/common/Loader';
import EmptyState from '../components/common/EmptyState';

const renderSection = (title: string, data: Record<string, unknown>) => (
  <Card title={title}>
    <div className="space-y-3">
      {Object.entries(data).map(([key, value]) => (
        <div key={key} className="premium-panel grid gap-2 sm:grid-cols-[180px_1fr]">
          <p className="text-sm font-semibold text-text">{key}</p>
          <pre className="whitespace-pre-wrap break-words text-sm leading-6 text-muted">{JSON.stringify(value, null, 2)}</pre>
        </div>
      ))}
    </div>
  </Card>
);

const AnalysisPage = () => {
  const [searchParams] = useSearchParams();
  const incidentId = searchParams.get('id');
  const [analysis, setAnalysis] = useState<Record<string, Record<string, unknown>> | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!incidentId) return;
    const fetchAnalysis = async () => {
      setIsLoading(true);
      try {
        const data = await analyzeIncident(incidentId);
        setAnalysis({
          incidentSummary: data.incidentSummary,
          context: data.context,
          riskAnalysis: data.riskAnalysis,
          recommendations: data.recommendations,
          approval: data.approval,
        });
      } catch (_err) {
        setError('Unable to load analysis.');
      } finally {
        setIsLoading(false);
      }
    };
    fetchAnalysis();
  }, [incidentId]);

  if (!incidentId) {
    return <EmptyState title="No incident selected" description="Select an incident from the list to run analysis." />;
  }

  if (isLoading) {
    return <Loader />;
  }

  if (error || !analysis) {
    return <div className="glass-card p-8 text-center text-muted">{error || 'No analysis available.'}</div>;
  }

  return (
    <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.45 }} className="space-y-6">
      <div>
        <p className="eyebrow">Agent Output</p>
        <h1 className="mt-2 text-3xl font-semibold text-text">AI Analysis</h1>
        <p className="mt-1 text-sm text-muted">Review the incident analysis generated by the backend.</p>
      </div>
      {Object.entries(analysis).map(([section, data]) => renderSection(section, data))}
    </motion.div>
  );
};

export default AnalysisPage;
